# Pandas Day 2: Data Selection, Filtering & Cleaning

## Week 3, Day 2 - From Looking to Doing

---

### Today's Journey (2.5 Hours)

| Part | Topic | Duration |
|------|-------|----------|
| 1 | Workflow Repetition (New Dataset) | ~20 min |
| 2 | Advanced Filtering | ~30 min |
| | **BREAK 1** | 10 min |
| 3 | Sorting Data | ~15 min |
| 4 | loc/iloc - Precise Selection | ~30 min |
| | **BREAK 2** | 10 min |
| 5 | Handling Missing Data | ~20 min |
| 6 | Mini-Project: Restaurant Analysis | ~25 min |
| 7 | Wrap Up & Preview | ~10 min |

---

```
TODAY'S PROMISE:

    BEFORE:
    ┌────────────────────────────────────────────────────────────────────┐
    │                                                                    │
    │   Dataset: 50 columns, 1 million rows                             │
    │   Question: "Show me California customers who spent > $10K"       │
    │                                                                    │
    │   😰 Without today's skills:                                       │
    │      • Scroll through data manually                               │
    │      • Write 15 lines of confusing code                           │
    │      • Make mistakes, debug for 30 minutes                        │
    │                                                                    │
    └────────────────────────────────────────────────────────────────────┘
    
    
    AFTER:
    ┌────────────────────────────────────────────────────────────────────┐
    │                                                                    │
    │   df.loc[(df['amount'] > 10000) & (df['state'] == 'CA'),          │
    │          ['customer', 'amount', 'date']]                          │
    │                                                                    │
    │   ✓ One line                                                       │
    │   ✓ 10 seconds                                                     │
    │   ✓ Exactly the data you need                                     │
    │                                                                    │
    └────────────────────────────────────────────────────────────────────┘
```

---

# Part 1: The Workflow (Building Instinct)

## First, Let's Lock In Yesterday's Foundation

Before we add new tools, we need the basics to be AUTOMATIC.

```
1. df.head()     - What does this data look like?
2. df.shape      - How much data do I have?
3. df.info()     - What types? What's missing?
4. df.describe() - What's the story in numbers?
```

---

## Setup

In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

plt.style.use('seaborn-v0_8-darkgrid')
%matplotlib inline
pd.set_option('display.max_rows', 100)

print("Ready to go!")

Ready to go!

In [2]:
# Load our dataset
flights = sns.load_dataset('flights')
print("Loaded!")

Loaded!

In [3]:
flights.head(10)

   year month  passengers
0  1949   Jan         112
1  1949   Feb         118
2  1949   Mar         132
3  1949   Apr         129
4  1949   May         121
5  1949   Jun         135
6  1949   Jul         148
7  1949   Aug         148
8  1949   Sep         136
9  1949   Oct         119

In [4]:
print(f"Shape: {flights.shape}")
print(f"That's {flights.shape[0]} months of data")

Shape: (144, 3)
That's 144 months of data

In [5]:
flights.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 144 entries, 0 to 143
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   year        144 non-null    int64
 1   month       144 non-null    category
 2   passengers  144 non-null    int64
dtypes: category(1), int64(2)
memory usage: 2.9 KB

In [6]:
flights.describe()

              year  passengers
count   144.000000  144.000000
mean   1954.500000  280.298611
std       3.464102  119.966317
min    1949.000000  104.000000
25%    1951.750000  180.000000
50%    1954.500000  265.500000
75%    1957.250000  360.500000
max    1960.000000  622.000000

## Your First Filter

Before we get to complex filtering, let's start with the basics.

In [7]:
# Basic filter: more than 400 passengers
high_traffic = flights[flights['passengers'] > 400]

print(f"High traffic months: {len(high_traffic)} out of {len(flights)}")
high_traffic.head()

High traffic months: 28 out of 144

     year month  passengers
90   1956   Jul         413
91   1956   Aug         405
101  1957   Jun         422
102  1957   Jul         465
103  1957   Aug         467

In [8]:
# Which months appear most?
high_traffic['month'].value_counts()

month
Jul    5
Aug    5
Sep    4
Jun    4
May    2
Oct    2
Dec    2
Mar    2
Jan    1
Apr    1
Feb    0
Nov    0
Name: count, dtype: int64

---

# Part 2: Advanced Filtering

## When One Condition Isn't Enough

```
REAL-WORLD QUESTIONS ARE COMPLEX:

    Simple question:     "Show me customers over 30"
                         df[df['age'] > 30]
    
    
    Real question:       "Show me customers over 30
                          AND from California
                          AND haven't bought in 6 months
                          AND opened our last email"
    
                         df[(condition1) & (condition2) & (condition3) & (condition4)]
    
    
    THE DIFFERENCE:
    ┌─────────────────────────────────────────────────────────────────────┐
    │                                                                     │
    │   People who can answer complex questions quickly → VALUABLE       │
    │   People who fumble for 30 minutes → NOT valuable                  │
    │                                                                     │
    └─────────────────────────────────────────────────────────────────────┘
```

---

## The Three Operators

```
THE LOGIC OPERATORS:

    ┌──────────┬─────────────┬──────────────────────────────────────────┐
    │ Operator │ Meaning     │ English                                  │
    ├──────────┼─────────────┼──────────────────────────────────────────┤
    │    &     │ AND         │ BOTH must be true                        │
    │    |     │ OR          │ AT LEAST ONE must be true                │
    │    ~     │ NOT         │ FLIP true ↔ false                        │
    └──────────┴─────────────┴──────────────────────────────────────────┘


⚠️  THE RULE THAT WILL SAVE YOU HOURS OF DEBUGGING:

    ┌─────────────────────────────────────────────────────────────────────┐
    │                                                                     │
    │   ALWAYS wrap each condition in parentheses!                       │
    │                                                                     │
    │   ❌ WRONG:   df[df['age'] > 30 & df['city'] == 'NYC']             │
    │              → ERROR! Python evaluates in wrong order              │
    │                                                                     │
    │   ✓ RIGHT:   df[(df['age'] > 30) & (df['city'] == 'NYC')]          │
    │              → Works perfectly                                      │
    │                                                                     │
    └─────────────────────────────────────────────────────────────────────┘
```

## AND: Both Conditions Must Be True

In [9]:
# Find July data from 1950 onward
# (year >= 1950) AND (month == 'Jul')

fifties_july = flights[(flights['year'] >= 1950) & (flights['month'] == 'Jul')]

print(f"July months from 1950+: {len(fifties_july)} rows")
fifties_july

July months from 1950+: 11 rows

     year month  passengers
18   1950   Jul         170
30   1951   Jul         199
42   1952   Jul         230
54   1953   Jul         264
66   1954   Jul         302
78   1955   Jul         364
90   1956   Jul         413
102  1957   Jul         465
114  1958   Jul         491
126  1959   Jul         548
138  1960   Jul         622

## OR: At Least One Condition Must Be True

In [10]:
# Find summer months - June OR July OR August

summer = flights[
    (flights['month'] == 'Jun') |
    (flights['month'] == 'Jul') |
    (flights['month'] == 'Aug')
]

print(f"Summer months: {len(summer)} rows")
summer.head()

Summer months: 36 rows

    year month  passengers
5   1949   Jun         135
6   1949   Jul         148
7   1949   Aug         148
17  1950   Jun         149
18  1950   Jul         170

## The Better Way: .isin()

```
THE UGLY WAY vs THE CLEAN WAY:

    ❌ UGLY (doesn't scale):
    
       (df['month'] == 'Jun') | (df['month'] == 'Jul') | (df['month'] == 'Aug')
       
       What if you need 20 values? 20 conditions, 19 pipes. Nightmare.
    
    
    ✓ CLEAN (scales beautifully):
    
       df['month'].isin(['Jun', 'Jul', 'Aug'])
       
       Need 20 values? Just add them to the list. Done.
    
    
    ┌─────────────────────────────────────────────────────────────────────┐
    │                                                                     │
    │   .isin() = "Is this value IN this list?"                          │
    │                                                                     │
    │   This is how professionals write pandas code.                     │
    │                                                                     │
    └─────────────────────────────────────────────────────────────────────┘
```

In [12]:
# Same result, MUCH cleaner
summer_months = ['Jun', 'Jul', 'Aug', 'Sep']
summer = flights[flights['month'].isin(summer_months)]

print(f"Summer months: {len(summer)} rows")
summer.head()

Summer months: 48 rows

    year month  passengers
5   1949   Jun         135
6   1949   Jul         148
7   1949   Aug         148
8   1949   Sep         136
17  1950   Jun         149

In [13]:
# Combine isin with other conditions
# Winter months in 1960
winter_months = ['Dec', 'Jan', 'Feb']

winter_60 = flights[
    (flights['month'].isin(winter_months)) &
    (flights['year'] == 1960)
]

print(f"Winter 1960: {len(winter_60)} rows")
winter_60

Winter 1960: 3 rows

     year month  passengers
132  1960   Jan         417
133  1960   Feb         391
143  1960   Dec         432

## Another Shortcut: .between()

Instead of:
```python
(value >= 100) & (value <= 200)
```

Use:
```python
value.between(100, 200)
```

In [14]:
# Find moderate traffic months (200-350 passengers)
moderate = flights[flights['passengers'].between(200, 350)]

print(f"Moderate traffic: {len(moderate)} rows")
moderate.head()

Moderate traffic: 55 rows

    year month  passengers
41  1952   Jun         218
42  1952   Jul         230
43  1952   Aug         242
44  1952   Sep         209
50  1953   Mar         236

## NOT: Inverting Conditions with ~

In [15]:
# Everything EXCEPT summer
non_summer = flights[~flights['month'].isin(['Jun', 'Jul', 'Aug'])]

print(f"Non-summer months: {len(non_summer)} rows")
print(f"Months included: {list(non_summer['month'].unique())}")

Non-summer months: 108 rows
Months included: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Sep', 'Oct', 'Nov', 'Dec']

## Let's Answer That Manager Question

Remember: "Summer months in the late 1950s with high traffic"

In [16]:
# Summer months (Jun, Jul, Aug)
# Late 1950s (year >= 1957)
# High traffic (passengers > 400)

answer = flights[
    (flights['month'].isin(['Jun', 'Jul', 'Aug'])) &
    (flights['year'] >= 1957) &
    (flights['passengers'] > 400)
]

print(f"Summer months, late 50s, high traffic: {len(answer)} rows")
answer

Summer months, late 50s, high traffic: 12 rows

     year month  passengers
101  1957   Jun         422
102  1957   Jul         465
103  1957   Aug         467
113  1958   Jun         435
114  1958   Jul         491
115  1958   Aug         505
125  1959   Jun         472
126  1959   Jul         548
127  1959   Aug         559
137  1960   Jun         535
138  1960   Jul         622
139  1960   Aug         606

## Filtering Cheat Sheet

| Need | Use | Example |
|------|-----|----------|
| Both conditions | `&` | `(A > 5) & (B < 10)` |
| Either condition | `\|` | `(A > 5) \| (B < 10)` |
| Value in list | `.isin()` | `col.isin(['x', 'y', 'z'])` |
| Numeric range | `.between()` | `col.between(10, 20)` |
| Invert/exclude | `~` | `~col.isin(['x', 'y'])` |

**Golden Rule**: Parentheses around EVERY condition!

## Quick Practice: Test Your Filtering (5 minutes)

**Try these yourself before I show the answers:**

1. Find all months from 1955 (just that year)
2. Find spring months (Mar, Apr, May) with passengers between 200-400
3. Find all months EXCEPT December

In [17]:
# Solution 1: All months from 1955
flights_1955 = flights[flights['year'] == 1955]
print(f"1955 data: {len(flights_1955)} rows")
flights_1955

1955 data: 12 rows

    year month  passengers
72  1955   Jan         242
73  1955   Feb         233
74  1955   Mar         267
75  1955   Apr         269
76  1955   May         270
77  1955   Jun         315
78  1955   Jul         364
79  1955   Aug         347
80  1955   Sep         312
81  1955   Oct         274
82  1955   Nov         237
83  1955   Dec         278

In [18]:
# Solution 2: Spring months (Mar, Apr, May) with passengers 200-400
spring_moderate = flights[
    (flights['month'].isin(['Mar', 'Apr', 'May'])) &
    (flights['passengers'].between(200, 400))
]
print(f"Spring with moderate traffic: {len(spring_moderate)} rows")
spring_moderate

Spring with moderate traffic: 19 rows

     year month  passengers
50   1953   Mar         236
51   1953   Apr         235
52   1953   May         229
62   1954   Mar         235
63   1954   Apr         227
64   1954   May         234
74   1955   Mar         267
75   1955   Apr         269
76   1955   May         270
86   1956   Mar         317
87   1956   Apr         313
88   1956   May         318
98   1957   Mar         356
99   1957   Apr         348
100  1957   May         355
110  1958   Mar         362
111  1958   Apr         348
112  1958   May         363
123  1959   Apr         396

In [19]:
# Solution 3: All months EXCEPT December
not_december = flights[~(flights['month'] == 'Dec')]
print(f"Non-December months: {len(not_december)} rows")
not_december.head()

Non-December months: 132 rows

   year month  passengers
0  1949   Jan         112
1  1949   Feb         118
2  1949   Mar         132
3  1949   Apr         129
4  1949   May         121

---

# Part 3: Sorting Data

## Finding the Extremes

---

In [22]:
# Sort ascending (smallest first) - default
flights.sort_values('passengers').head(10)

    year month  passengers
10  1949   Nov         104
0   1949   Jan         112
22  1950   Nov         114
12  1950   Jan         115
11  1949   Dec         118
1   1949   Feb         118
9   1949   Oct         119
4   1949   May         121
16  1950   May         125
13  1950   Feb         126

In [23]:
# Sort descending (largest first)
flights.sort_values('passengers', ascending=False).head(10)

     year month  passengers
138  1960   Jul         622
139  1960   Aug         606
127  1959   Aug         559
126  1959   Jul         548
137  1960   Jun         535
140  1960   Sep         508
115  1958   Aug         505
114  1958   Jul         491
136  1960   May         472
125  1959   Jun         472

In [24]:
# Even faster: nlargest and nsmallest
print("Top 5 busiest months:")
flights.nlargest(5, 'passengers')

Top 5 busiest months:

     year month  passengers
138  1960   Jul         622
139  1960   Aug         606
127  1959   Aug         559
126  1959   Jul         548
137  1960   Jun         535

In [25]:
print("Top 5 quietest months:")
flights.nsmallest(5, 'passengers')

Top 5 quietest months:

    year month  passengers
10  1949   Nov         104
0   1949   Jan         112
22  1950   Nov         114
12  1950   Jan         115
1   1949   Feb         118

## Multi-Column Sorting

What if you need to sort by multiple criteria?

In [27]:
# Sort by year, then by passengers within each year
flights.sort_values(['year', 'passengers'], ascending=[True, False]).head(24)

    year month  passengers
6   1949   Jul         148
7   1949   Aug         148
8   1949   Sep         136
5   1949   Jun         135
2   1949   Mar         132
3   1949   Apr         129
4   1949   May         121
9   1949   Oct         119
1   1949   Feb         118
11  1949   Dec         118
0   1949   Jan         112
10  1949   Nov         104
18  1950   Jul         170
19  1950   Aug         170
20  1950   Sep         158
17  1950   Jun         149
14  1950   Mar         141
23  1950   Dec         140
15  1950   Apr         135
21  1950   Oct         133
13  1950   Feb         126
16  1950   May         125
12  1950   Jan         115
22  1950   Nov         114

---

## BREAK 1 (10 Minutes)

### What we've covered:
- Workflow repetition (your safety net)
- Advanced filtering (&, |, isin, between, ~)
- Sorting (sort_values, nlargest, nsmallest)

### Coming up - THE most important part:
- **loc and iloc** - This is the skill that separates beginners from professionals

---

---

# Part 4: loc and iloc - Precision Selection

## This Is What Separates Amateurs from Professionals

---

## The Core Difference

```
iloc vs loc: TWO WAYS TO SELECT DATA

    ┌─────────────────────────────────────────────────────────────────────┐
    │                                                                     │
    │   iloc = "Integer Location"          loc = "Label Location"        │
    │   ─────────────────────────          ─────────────────────         │
    │                                                                     │
    │   Select by POSITION                 Select by LABELS/CONDITIONS   │
    │   (0, 1, 2, 3...)                    (names, True/False)           │
    │                                                                     │
    │   "Give me row NUMBER 5"             "Give me rows WHERE age > 30" │
    │                                                                     │
    │   Think: COUNTING                    Think: DESCRIBING             │
    │                                                                     │
    └─────────────────────────────────────────────────────────────────────┘


    ANALOGY:
    
    iloc  →  "Give me the 5th person in line"
    loc   →  "Give me everyone wearing a red shirt"
```

## iloc - Selecting by Position

In [28]:
# Single row (position 0 = first row)
flights.iloc[0]

year          1949
month          Jan
passengers     112
Name: 0, dtype: object

In [29]:
# Single cell: row 0, column 2
flights.iloc[0, 2]

np.int64(112)

In [30]:
# Range of rows: first 5 (positions 0-4)
flights.iloc[0:5]

   year month  passengers
0  1949   Jan         112
1  1949   Feb         118
2  1949   Mar         132
3  1949   Apr         129
4  1949   May         121

In [31]:
# Rows AND columns: first 5 rows, first 2 columns
flights.iloc[0:5, 0:2]

   year month
0  1949   Jan
1  1949   Feb
2  1949   Mar
3  1949   Apr
4  1949   May

In [33]:
flights.iloc[5:10]

   year month  passengers
5  1949   Jun         135
6  1949   Jul         148
7  1949   Aug         148
8  1949   Sep         136
9  1949   Oct         119

In [34]:
flights.iloc[5:10:2] # adding a step of 2

   year month  passengers
5  1949   Jun         135
7  1949   Aug         148
9  1949   Oct         119

In [32]:
# Last 5 rows (negative indexing)
flights.iloc[-5:]

     year month  passengers
139  1960   Aug         606
140  1960   Sep         508
141  1960   Oct         461
142  1960   Nov         390
143  1960   Dec         432

## loc - Selecting by Labels

In [35]:
# Row with index 0, column named 'passengers'
flights.loc[0, 'passengers']

np.int64(112)

In [38]:
# Specific rows and columns by name
flights.loc[0:4, ['year', 'month', 'passengers']]

   year month  passengers
0  1949   Jan         112
1  1949   Feb         118
2  1949   Mar         132
3  1949   Apr         129
4  1949   May         121

In [39]:
# CRITICAL DIFFERENCE
print(f"iloc[0:5] returns {len(flights.iloc[0:5])} rows (excludes position 5)")
print(f"loc[0:5] returns {len(flights.loc[0:5])} rows (INCLUDES index 5)")

iloc[0:5] returns 5 rows (excludes position 5)
loc[0:5] returns 6 rows (INCLUDES index 5)

## The Power Move: loc + Conditions

```
THE PATTERN THAT HANDLES 80% OF YOUR DATA WORK:

    ┌─────────────────────────────────────────────────────────────────────┐
    │                                                                     │
    │   df.loc[condition, ['column1', 'column2']]                        │
    │          ─────────  ──────────────────────                         │
    │              │               │                                      │
    │              │               └── WHICH COLUMNS to show             │
    │              │                                                      │
    │              └── WHICH ROWS to include                             │
    │                                                                     │
    │                                                                     │
    │   English: "Give me rows WHERE this is true,                       │
    │             and ONLY SHOW me these columns."                       │
    │                                                                     │
    └─────────────────────────────────────────────────────────────────────┘


    EXAMPLE:
    
    "Transactions over $10K from California"
    
    df.loc[(df['amount'] > 10000) & (df['state'] == 'CA'),
           ['customer', 'amount', 'date']]
    
    One line. Done.
```

In [41]:
# High traffic months - only show year, month, passengers
flights.loc[flights['passengers'] > 500, ['year', 'month', 'passengers']]

     year month  passengers
115  1958   Aug         505
126  1959   Jul         548
127  1959   Aug         559
137  1960   Jun         535
138  1960   Jul         622
139  1960   Aug         606
140  1960   Sep         508

In [42]:
# Multiple conditions - late 50s high traffic
flights.loc[
    (flights['year'] >= 1957) & (flights['passengers'] > 450),
    ['year', 'month', 'passengers']
]

     year month  passengers
102  1957   Jul         465
103  1957   Aug         467
114  1958   Jul         491
115  1958   Aug         505
125  1959   Jun         472
126  1959   Jul         548
127  1959   Aug         559
128  1959   Sep         463
135  1960   Apr         461
136  1960   May         472
137  1960   Jun         535
138  1960   Jul         622
139  1960   Aug         606
140  1960   Sep         508
141  1960   Oct         461

## loc Also Sets Values

In [43]:
# Create a copy (always!)
df = flights.copy()

# Create a new column based on condition
df.loc[df['passengers'] > 400, 'traffic'] = 'High'
df.loc[df['passengers'] <= 400, 'traffic'] = 'Normal'

df[['year', 'month', 'passengers', 'traffic']].head(15)

    year month  passengers traffic
0   1949   Jan         112  Normal
1   1949   Feb         118  Normal
2   1949   Mar         132  Normal
3   1949   Apr         129  Normal
4   1949   May         121  Normal
5   1949   Jun         135  Normal
6   1949   Jul         148  Normal
7   1949   Aug         148  Normal
8   1949   Sep         136  Normal
9   1949   Oct         119  Normal
10  1949   Nov         104  Normal
11  1949   Dec         118  Normal
12  1950   Jan         115  Normal
13  1950   Feb         126  Normal
14  1950   Mar         141  Normal

## Quick Reference

| What you need | Use this |
|---------------|----------|
| Row by position | `iloc[5]` |
| Last 10 rows | `iloc[-10:]` |
| Rows 10-20 | `iloc[10:21]` |
| Filter + select columns | `loc[condition, ['col1', 'col2']]` |
| Set values by condition | `loc[condition, 'col'] = value` |

**Rule of thumb**: iloc for positions, loc for everything else.

---

## BREAK 2 (10 Minutes)

### What we've covered:
- **loc** - The power pattern: `df.loc[condition, ['col1', 'col2']]`
- **iloc** - Position-based selection for when you need row numbers
- The critical difference: iloc excludes endpoint, loc includes it
- Setting values with loc

### Coming up:
- **Handling Missing Data** - The reality of messy real-world data

---

# Part 5: Handling Missing Data

## Welcome to Reality

```
THE TRUTH ABOUT REAL DATA:

    ┌─────────────────────────────────────────────────────────────────────┐
    │                                                                     │
    │   "I've never - not ONCE - received a dataset without              │
    │    missing data."                                                   │
    │                                        - Every data analyst ever   │
    │                                                                     │
    └─────────────────────────────────────────────────────────────────────┘
    
    
    WHY DATA GOES MISSING:
    
    🔌 Sensors fail              📝 People skip survey questions
    🐛 Databases have bugs       📡 Data corrupted in transit
    🚫 Privacy restrictions      ⏰ Collection started late
    
    
    THE STAT:
    
    "Data analysts spend 80% of their time cleaning data."
    
    That might be LOW.
```

In [44]:
# Load titanic - real data with real problems
titanic = sns.load_dataset('titanic')

print(f"Loaded {len(titanic)} passenger records")
titanic.head()

Loaded 891 passenger records

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [45]:
# The damage report
print("Missing values:")
print(titanic.isna().sum())
print(f"\nTotal rows: {len(titanic)}")

Missing values:
survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

Total rows: 891

## Option 1: Just Drop Missing Rows

In [46]:
# The naive approach
clean = titanic.dropna()

print(f"Before: {len(titanic)} rows")
print(f"After: {len(clean)} rows")
print(f"Lost: {len(titanic) - len(clean)} rows ({(len(titanic)-len(clean))/len(titanic)*100:.0f}%)")

Before: 891 rows
After: 182 rows
Lost: 709 rows (80%)

## Option 2: Fill Missing Values

In [47]:
# For numbers: fill with median (not mean - outliers!)
df = titanic.copy()
median_age = df['age'].median()

print(f"Median age: {median_age}")

df['age'] = df['age'].fillna(median_age)
print(f"Missing ages now: {df['age'].isna().sum()}")

Median age: 28.0
Missing ages now: 0

In [48]:
# For categories: fill with mode (most common)
df = titanic.copy()
most_common = df['embarked'].mode()[0]

print(f"Most common port: {most_common}")

df['embarked'] = df['embarked'].fillna(most_common)
print(f"Missing embarked now: {df['embarked'].isna().sum()}")

Most common port: S
Missing embarked now: 0

## Option 3: Drop Hopeless Columns

In [49]:
# Deck is 77% missing - just drop it
df = titanic.drop(columns=['deck'])

print(f"Dropped 'deck' column")
print(f"Columns: {len(titanic.columns)} -> {len(df.columns)}")

Dropped 'deck' column
Columns: 15 -> 14

## The Real-World Recipe

In [50]:
# What professionals actually do
df = titanic.copy()

# 1. Drop columns that are >50% missing
df = df.drop(columns=['deck'])

# 2. Fill numbers with median
df['age'] = df['age'].fillna(df['age'].median())

# 3. Fill categories with mode
df['embarked'] = df['embarked'].fillna(df['embarked'].mode()[0])
df['embark_town'] = df['embark_town'].fillna(df['embark_town'].mode()[0])

print("Remaining missing values:")
print(df.isna().sum().sum())
print(f"\nRows kept: {len(df)} / {len(titanic)} = 100%")

Remaining missing values:
0

Rows kept: 891 / 891 = 100%

## Missing Data Decision Tree

```
HOW TO HANDLE MISSING DATA:

                        ┌─────────────────────────┐
                        │  Column > 50% missing?  │
                        └───────────┬─────────────┘
                                    │
                    ┌───────────────┴───────────────┐
                    │                               │
                   YES                             NO
                    │                               │
                    ▼                               ▼
            ┌───────────────┐           ┌─────────────────────────┐
            │  DROP the     │           │  < 5% of rows missing?  │
            │  column       │           └───────────┬─────────────┘
            └───────────────┘                       │
                                    ┌───────────────┴───────────────┐
                                    │                               │
                                   YES                             NO
                                    │                               │
                                    ▼                               ▼
                            ┌───────────────┐           ┌───────────────────────┐
                            │  dropna()     │           │  What type of data?   │
                            │  is fine      │           └───────────┬───────────┘
                            └───────────────┘                       │
                                                    ┌───────────────┴───────────────┐
                                                    │                               │
                                                NUMERIC                         CATEGORICAL
                                                    │                               │
                                                    ▼                               ▼
                                            ┌───────────────┐               ┌───────────────┐
                                            │ fillna(median)│               │ fillna(mode)  │
                                            └───────────────┘               └───────────────┘
```

---

# Part 6: Mini-Project - Restaurant Analysis

## Put It All Together (20 minutes)

```
THE SCENARIO:

    You're a data analyst for a restaurant consulting firm.
    
    A client (restaurant owner) wants answers to these questions:
    
    1. "Which day brings in the most tips?"
    2. "Do dinner parties tip better than lunch parties?"
    3. "Who are my best customers - and what do they have in common?"
    4. "My data has some issues - can you clean it up?"
    
    
    YOU HAVE 15 MINUTES TO ANSWER THESE QUESTIONS.
    
    Use everything you learned today:
    • Filtering (single and multiple conditions)
    • Sorting (finding the top/bottom)
    • loc (selecting specific rows and columns)
    • Missing data handling
```

---

In [51]:
# Load the restaurant tips dataset
tips = sns.load_dataset('tips')

# Quick inspection - what are we working with?
print(f"Dataset: {tips.shape[0]} rows, {tips.shape[1]} columns")
print(f"\nColumns: {list(tips.columns)}")
tips.head(10)

Dataset: 244 rows, 7 columns

Columns: ['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size']

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
5       25.29  4.71    Male     No  Sun  Dinner     4
6        8.77  2.00    Male     No  Sun  Dinner     2
7       26.88  3.12    Male     No  Sun  Dinner     4
8       15.04  1.96    Male     No  Sun  Dinner     2
9       14.78  3.23    Male     No  Sun  Dinner     2

In [52]:
# Check for missing data
print("Missing values:")
print(tips.isna().sum())

Missing values:
total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [53]:
# Let's make it realistic - add some missing data
tips_messy = tips.copy()

# Randomly remove some tip values (simulating data entry errors)
np.random.seed(42)
missing_idx = np.random.choice(tips_messy.index, size=15, replace=False)
tips_messy.loc[missing_idx, 'tip'] = np.nan

print(f"Now we have {tips_messy['tip'].isna().sum()} missing tip values")
print("\nThis is your working dataset: tips_messy")

Now we have 15 missing tip values

This is your working dataset: tips_messy

## Your Tasks (15 minutes)

```
QUESTIONS FROM THE RESTAURANT OWNER:

    Q1: "Which day of the week has the highest AVERAGE tip?"
        → Use filtering and/or sorting
        → Show the day and the average tip
    
    Q2: "Show me all dinner parties of 4+ people who tipped over $5"
        → Multiple conditions
        → Use loc to show: day, time, size, total_bill, tip
    
    Q3: "Who are my top 10 tippers? What do they have in common?"
        → Sort to find top 10
        → Look at their characteristics (time, day, size, smoker)
    
    Q4: "Clean up the missing tip data - fill it reasonably"
        → Handle the 15 missing tip values
        → Verify no missing data remains


START WORKING! I'll show solutions in 15 minutes.
```

In [ ]:
# YOUR WORK HERE - Q1: Which day has highest average tip?

In [ ]:
# YOUR WORK HERE - Q2: Dinner parties 4+ people, tip > $5

In [ ]:
# YOUR WORK HERE - Q3: Top 10 tippers

In [ ]:
# YOUR WORK HERE - Q4: Clean missing tip data

---

## Solutions

---

In [54]:
# SOLUTION Q1: Which day has highest average tip?
# We need groupby for proper averages (Day 3 topic), but we can approximate:

print("Average tip by day:")
for day in tips['day'].unique():
    avg = tips[tips['day'] == day]['tip'].mean()
    print(f"  {day}: ${avg:.2f}")

# Or use value_counts to see which days are busiest
print("\nNumber of transactions by day:")
print(tips['day'].value_counts())

Average tip by day:
  Sun: $3.26
  Sat: $2.99
  Thur: $2.77
  Fri: $2.73

Number of transactions by day:
day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [55]:
# SOLUTION Q2: Dinner parties 4+ people, tip > $5
# Multiple conditions + loc for specific columns

big_dinner_tippers = tips.loc[
    (tips['time'] == 'Dinner') &
    (tips['size'] >= 4) &
    (tips['tip'] > 5),
    ['day', 'time', 'size', 'total_bill', 'tip']
]

print(f"Found {len(big_dinner_tippers)} dinner parties of 4+ with tips over $5:")
big_dinner_tippers

Found 10 dinner parties of 4+ with tips over $5:

     day    time  size  total_bill   tip
23   Sat  Dinner     4       39.42  7.58
44   Sun  Dinner     4       30.40  5.60
47   Sun  Dinner     4       32.40  6.00
52   Sun  Dinner     4       34.81  5.20
59   Sat  Dinner     4       48.27  6.73
116  Sun  Dinner     4       29.93  5.07
155  Sun  Dinner     5       29.85  5.14
183  Sun  Dinner     4       23.17  6.50
211  Sat  Dinner     4       25.89  5.16
212  Sat  Dinner     4       48.33  9.00

In [56]:
# SOLUTION Q3: Top 10 tippers - who are they?
top_tippers = tips.nlargest(10, 'tip')

print("Top 10 tippers:")
print(top_tippers)

print("\n" + "="*50)
print("PATTERNS IN TOP TIPPERS:")
print("="*50)
print(f"\nTime of day: {top_tippers['time'].value_counts().to_dict()}")
print(f"Day of week: {top_tippers['day'].value_counts().to_dict()}")
print(f"Smoker: {top_tippers['smoker'].value_counts().to_dict()}")
print(f"Average party size: {top_tippers['size'].mean():.1f}")
print(f"Average total bill: ${top_tippers['total_bill'].mean():.2f}")

Top 10 tippers:
     total_bill    tip     sex smoker   day    time  size
170       50.81  10.00    Male    Yes   Sat  Dinner     3
212       48.33   9.00    Male     No   Sat  Dinner     4
23        39.42   7.58    Male     No   Sat  Dinner     4
59        48.27   6.73    Male     No   Sat  Dinner     4
141       34.30   6.70    Male     No  Thur   Lunch     6
183       23.17   6.50    Male    Yes   Sun  Dinner     4
214       28.17   6.50  Female    Yes   Sat  Dinner     3
47        32.40   6.00    Male     No   Sun  Dinner     4
239       29.03   5.92    Male     No   Sat  Dinner     3
88        24.71   5.85    Male     No  Thur   Lunch     2

==================================================
PATTERNS IN TOP TIPPERS:
==================================================

Time of day: {'Dinner': 8, 'Lunch': 2}
Day of week: {'Sat': 6, 'Thur': 2, 'Sun': 2, 'Fri': 0}
Smoker: {'No': 7, 'Yes': 3}
Average party size: 3.7
Average total bill: $35.86

In [57]:
# SOLUTION Q4: Clean missing tip data
tips_clean = tips_messy.copy()

# Check before
print(f"Missing tips before: {tips_clean['tip'].isna().sum()}")

# Fill with median (tip is numeric)
median_tip = tips_clean['tip'].median()
print(f"Median tip: ${median_tip:.2f}")

tips_clean['tip'] = tips_clean['tip'].fillna(median_tip)

# Verify
print(f"Missing tips after: {tips_clean['tip'].isna().sum()}")
print(f"\nData cleaned! All {len(tips_clean)} rows preserved.")

Missing tips before: 15
Median tip: $3.00
Missing tips after: 0

Data cleaned! All 244 rows preserved.

## Today's Key Patterns

### The Filtering Pattern
```python
df[(condition1) & (condition2)]  # Always use parentheses!
df[df['col'].isin(['a', 'b', 'c'])]  # Clean multi-value check
```

### The Selection Pattern (MOST IMPORTANT)
```python
df.loc[condition, ['col1', 'col2']]  # Filter rows + select columns
```

### The Cleaning Pattern
```python
df['num_col'].fillna(df['num_col'].median())  # Numbers
df['cat_col'].fillna(df['cat_col'].mode()[0])  # Categories
```

## Tomorrow: Day 3 Preview

- **GroupBy with .agg()** - Multiple statistics at once
- **DateTime operations** - Working with time
- **Merging datasets** - Combining data sources
- **Visualization** - Telling stories with charts

## Practice Tonight

Focus on **loc** - it's the skill that matters most.

**With flights:**
1. Find all 1960 data, showing only month and passengers
2. Find summer months with passengers between 300-500
3. Create a column 'era': 'Early' for year < 1955, 'Late' for year >= 1955

**With titanic:**
4. Find survivors over 50, showing age, sex, class, survived
5. Find passengers who paid more than $100, weren't in first class
6. Clean the age column and create age groups: Child (<18), Adult (18-60), Senior (60+)